- name: Setup dev environment
  hosts: all

  roles:
    - role: geerlingguy.nodejs
      become: yes
    - role: ktile
      become: yes
    - role: geonotebook
      geonotebook_version: master
      use_system_python_gdal: true
