---
# file: roles/jupyter/tasks/main.yml
- name: make sure necessary packages are installed
  apt:
    name: "{{item}}"
    state: present
    update_cache: yes
  with_items:
    - python3
    - python3-setuptools
    - python3-dev
    - python3-pip
    - python
    - python-setuptools
    - python-dev
    - sudo
    - npm
    - nodejs-legacy
    - git

- name: install npm package configurable-http-proxy
  npm:
    name: configurable-http-proxy
    global: yes
    state: present

- name: add jupyter group
  group:
    name: jupyter
    state: present

- name: add jupyter user
  user:
    name: jupyter
    state: present
    groups: jupyter,shadow
    password: "{{jupyterpw}}"

- name: add additional notebook users
  user:
    name: "{{ item.username }}"
    state: present
    groups: jupyter
    password: "{{ item.password }}"
  when: notebook_users is defined
  with_items: "{{ notebook_users }}"

- name: create jupyterhub folder in etc
  file:
    path: /etc/jupyterhub
    state: directory
    mode: 0755
    owner: jupyter
    group: jupyter
  tags: jupyter

- name: copy jupyterhub sudospawner sudo config
  copy:
    src: sudo_jupyter
    dest: /etc/sudoers.d/jupyter
    mode: 0440
    owner: root
    group: root
  tags: jupyter

- name: copy requirements file for jupyterhub
  copy:
    src: requirements.txt
    dest: /root/jupyterhub_requirements.txt
  tags: jupyter

- name: install jupyter, jupyterhub, sudospawner via pip3
  pip:
    executable: pip3
    requirements: "/root/jupyterhub_requirements.txt"
    extra_args: '--upgrade'
  tags: jupyter

- name: configure jupyterhub
  command: /usr/local/bin/jupyterhub --generate-config
  args:
    chdir: /etc/jupyterhub/
    creates: /etc/jupyterhub/jupyterhub_config.py
  tags: jupyter

- name: set jupyterhub admin user
  lineinfile:
    dest: /etc/jupyterhub/jupyterhub_config.py
    line: "c.Authenticator.admin_users = {'jupyter'}"
  tags: jupyter

- name: set jupyterhub create users
  lineinfile:
    dest: /etc/jupyterhub/jupyterhub_config.py
    line: "c.LocalAuthenticator.create_system_users = True"
  tags: jupyter

- name: install jupyterhub service
  copy:
    src: jupyterhub.service
    dest: /lib/systemd/system/jupyterhub.service
    mode: 644
    owner: root
    group: root
  tags: jupyter

- name: Ensure hostname is in /etc/hosts file
  lineinfile:
    dest: /etc/hosts
    regexp: "{{ansible_hostname}}"
    line: "{{ansible_default_ipv4.address}}  {{ansible_hostname}}"
  tags: jupyter

- name: create self-signed SSL cert
  command: openssl req -new -nodes -x509 -subj "/C=NA/ST=NA/L=NA/O=NA/CN=${ansible_fqdn}" -days 3650 -keyout /etc/jupyterhub/server.key -out /etc/jupyterhub/server.crt -extensions v3_ca creates=/etc/jupyterhub/server.crt

- name: set jupyterhub certificate
  lineinfile:
    dest: /etc/jupyterhub/jupyterhub_config.py
    line: "c.JupyterHub.ssl_cert = '/etc/jupyterhub/server.crt'"

- name: set jupyterhub certificate
  lineinfile:
    dest: /etc/jupyterhub/jupyterhub_config.py
    line: "c.JupyterHub.ssl_key = '/etc/jupyterhub/server.key'"

- name: Explicitly set proxy to listen on all interfaces
  lineinfile:
    dest: /etc/jupyterhub/jupyterhub_config.py
    line: "c.JupyterHub.ip = '0.0.0.0'"

- name: start jupyterhub
  service:
    name: jupyterhub
    enabled: yes
    state: started
  tags: jupyter
